project:
  type: book

book:
  title: "MISA: Minimal Instruction Set Architecture"
  author: "Jonathan Uhler"
  date: "2026-05-01"
  chapters:
    - index.qmd
    - isa.qmd
    - toolchain.qmd

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



