# Toolchain

The MISA project provides a standard toolchain for low-level development of programs on a processor
supporting the full MISA architecture. This includes an assembler, linker, some debug/analysis
tools, and a reference simulator.

This chapter covers the usage and technical details of the toolchain for building programs. That is,
all components of the MISA software package except the functional simulator.

## Assembler

`misa-as` in the reference assembler for the MISA instruction set architecture described in Chapter
1 of this document. It supports all the behavior of the ISA chapter, including the recommended
pseudo instructions and assembler macros.

Using `misa-as` is similar to an abbreviated version of the GNU `as` assemblers and others like it.
For a full description, see the help text at `misa-as --help`. In short, there are two common ways
to use the assembler:

1) Assembling source files to a binary: `misa-as file1.S file2.S ... fileN.S`
2) Assembling source files to object files: `misa-as -a file1.S file2.S ... fileN.S`

The assembler produces object files in a simple format accepted by the MISA linker. By default,
assembling will also invoke the linker to produce a final binary, although this step can be
omitted.

### Assembler Pipeline

The `misa-as` assembler is a wrapper CLI utility for several core binaries including the assembler,
but also the preprocessor and linker.

Assembling with no early-exit flags (e.g. `-p` or `-a`) runs provided files through a multi-step
pipeline:

1) All assembly source files are passed to the MISA preprocessor to resolve any preprocessor
   directives. The pipeline can be stopped after this stage with the `-p` flag.
2) The preprocessed output files are passed to the MISA assembler, which produces object files. The
   pipeline can be stopped after this stage with the `-a` flag.
3) The generated object files, as well as any non-source files originally passed to `misa-as`, are
   passed to the MISA linker to produce the final flat binary.

### Assembler Semantics

#### Instructions

`misa-as` supports the instruction semantics defined in the instruction "Usages" of the ISA chapter.
Opcodes and instruction operands are not comma-separated, and are case-insensitive.

#### Labels

Labels are programmer-defined symbols in assembly source code that are resolved to specific
addresses by the linker. Labels are C-style identifiers (containg the characters '_', a-z, A-Z, and
0-9, but not starting with 0-9) which end with a colon (':').

Label names are global to a binary at the linking stage, and can only be defined once. Assembly
written for the MISA standard library and other system code reserves double-underscore prefix `__`
for "local" labels. The recommended convention local labels in created by compilers and non-library
assembly is a single-underscore prefix `_`. In both cases, local labels should use the name of
their containing function as a discriminant. Compilers are encouraged to support name mangling for
global function labels.

During linking, labels used as instruction operands will be resolved to the address of the
first instruction after the label. For example, consider the following code:

```asm
    SET RA 0
    SET RB 10
loop:
    SET2 RYZ loop
    JMP LESS RA RB
```

In this case, the label `loop` has the relative address in this code of 0x0004, and refers to
the `SET2` instruction.

#### Assembler Directives

`misa-as` supports several assembler directives that change the behavior of the assembler and its
code generation. Directives are C-style reserved identifiers that begin with a period ('.') and
may take one or more operands.

The following directives are currently supported by `misa-as`:

- `.word <Word8>`: Emits the raw byte `<Word8>` in the generated code at the location of the
  directive
- `.array <Word8> [Word8...]`: Emits the raw bytes `<Word8> [Word8...]` in the generated code at the
  location of the directive. Earlier bytes in the array definition will be placed at lower
  addresses. `.array` is equivalent to many consecutive `.word` directives
- `.section <String>`: Defines for the linker that all the following code until the next
  section directive should be placed in a section called `<String>`
  
#### Preprocessor Directives

`misa-as` also supports preprocessor directives, but these are not resolved by the assembler
directly. See the section of the MISA preprocessor `misa-pr` for more information on syntax.
Preprocessor directives are resolved by the assembler before the assembly or linking phases.

### MISA Linkable Format

Object files produced by `misa-as` are in the custom `MISA_LF` linkable format, which are binary
files that contain:

- The assembled source code for one or more sections defined in a single assembler translation unit.
- A list of symbols (assembler labels) defined in the translation unit, along with their addresses
  relative to the beginning of the object file's machine code.
- A list of symbols required (not defined) by the translation unit during the linking phase, along
  with the address relative to the beginning of the object file's machine code where the symbol
  is needed.
  
#### Object File Description
  
Binary object files and all fields within them are encoded with little endian byte order. Each
object file contains the following information:

| Length   | Type    | Content                                                                                              |
|--------------|-------------|-----------------------------------------------------------------------------------------|
| 8        | String  | The string `MISA_LF `, where `M` is the least significant byte and ` ` is the most significant byte. |
| 2        | Word16  | The number of sections present in the object file.                                                   |
| Variable | Section | The content of each section, repeated as many times as specified in the length field.                |

#### Object File Section Description

Each section contains the following information:

| Length   | Type       | Content                                                                     |
|--------------|-------------|-----------------------------------------------------------------------------------------|
| 2        | Word16     | The length in bytes of the section name string field.                       |
| Variable | String     | The name of the section as defined with the `.section` assembler directive. |
| Variable | Code       | The content of the assembled machine code for the specified section.        |
| Variable | SymTable   | The table of symbols defined by the code in the specified section.          |
| Variable | RelocTable | The table of relocations required by the code in the specified section.     |

#### Object File Code Description

Each code table contains the following information:

| Length   | Type    | Content                                  |
|--------------|-------------|-----------------------------------------------------------------------------------------|
| 2        | Word16  | The length in bytes of the machine code. |
| Variable | [Word8] | The machine code.                        |

#### Object File Symbol Table Description

Each symbol table contains the following information:

| Length   | Type   | Content                                    |
|--------------|-------------|-----------------------------------------------------------------------------------------|
| 2        | Word16 | The number of symbols in the symbol table. |
| Variable | [Sym]  | The list of symbols.                       |

Each entry in the symbol table contains the following information:

| Length   | Type   | Content                                                                        |
|--------------|-------------|-----------------------------------------------------------------------------------------|
| 2        | Word16 | The address relative to the start of the code table that the symbol points to. |
| 2        | Word16 | The length in bytes of the symbol's string name.                               |
| Variable | String | The string name of the symbol.                                                 |

#### Object File Relocation Table Description

Each relocation table contains the following information:

| Length   | Type    | Content                                        |
|--------------|-------------|-----------------------------------------------------------------------------------------|
| 2        | Word16  | The number of relocations in the symbol table. |
| Variable | [Reloc] | The list of relocations.                       |

Each entry in the relocation table contains the following information:

| Length   | Type   | Content                                                                                                                              |
|--------------|-------------|-----------------------------------------------------------------------------------------|
| 1        | Word8  | Whether the byte at the relocation address must be filled with the high (0x01) or low (0x00) half of the relocated symbol's address. |
| 2        | Word16 | The address relative to the start of the code table of the byte that needs to be filled by the linker.                               |
| 2        | Word16 | The length in bytes of the relocation's string name.                                                                                 |
| Variable | String | The string name of the required symbol for relocation.                                                                               |

## Linker

`misa-ld` is the reference linker for the MISA_LF linkable format of object files. It uses memory
map files to place the code sections of one or more object files into a flat binary, resolving
symbol positions along the way.

## Other Tools
